version: '3'
services:
  db:
    image: postgres
    restart: always 
    env_file:
      - ./.env
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    container_name: CMPapijardineria
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data 